name: ario3
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2021.11
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.9.0
  - anaconda-project=0.10.2
  - anyio=2.2.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - arrow-cpp=4.0.1
  - asn1crypto=1.4.0
  - astroid=2.6.6
  - astropy=5.0
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.6.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - bitarray=2.3.5
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boost-cpp=1.73.0
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.11.0
  - conda-content-trust=0.1.1
  - conda-pack=0.6.0
  - conda-package-handling=1.7.3
  - conda-token=0.3.0
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=36.0.0
  - curl=7.71.1
  - cycler=0.11.0
  - cython=0.29.25
  - cytoolz=0.11.0
  - daal4py=2021.4.0
  - dal=2021.4.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2021.10.0
  - docutils=0.18.1
  - double-conversion=3.1.5
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - expat=2.4.1
  - fastcache=1.1.0
  - filelock=3.4.2
  - flake8=3.9.2
  - flask=1.1.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fribidi=1.0.10
  - fsspec=2022.1.0
  - get_terminal_size=1.0.0
  - gevent=21.8.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.0.8
  - graphite2=1.3.14
  - greenlet=1.1.1
  - grpc-cpp=1.26.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - harfbuzz=2.8.1
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.3.0
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=23.4.0
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libboost=1.73.0
  - libcurl=7.71.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblief=0.10.1
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libthrift=0.13.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.34.0
  - locket=0.2.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - more-itertools=8.12.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nltk=3.6.5
  - nose=1.3.7
  - notebook=6.4.6
  - numba=0.51.2
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - numpydoc=1.2
  - odfpy=1.4.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1m
  - orc=1.6.7
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - pango=1.45.3
  - parso=0.8.3
  - partd=1.2.0
  - patchelf=0.13
  - path=16.2.0
  - path.py=12.5.0
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - patsy=0.5.2
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=20.2.4
  - pixman=0.40.0
  - pkginfo=1.8.2
  - pluggy=1.0.0
  - ply=3.11
  - poyo=0.5.0
  - progressbar2=3.37.1
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pyarrow=4.0.1
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycurl=7.44.0
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pymrio=0.4.6
  - pyodbc=4.0.32
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.5
  - pytest-runner=5.3.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python-utils=2.5.6
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.1.1
  - qtpy=1.11.2
  - re2=2020.11.01
  - readline=8.0
  - regex=2021.11.2
  - requests=2.27.1
  - ripgrep=12.1.1
  - rope=0.22.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scikit-learn-intelex=2021.4.0
  - scipy=1.7.3
  - seaborn=0.11.2
  - secretstorage=3.3.1
  - send2trash=1.8.0
  - setuptools=50.3.0
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=3.5.3
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.4.27
  - sqlite=3.33.0
  - statsmodels=0.13.0
  - sympy=1.9
  - tbb=2021.5.0
  - tbb4py=2021.5.0
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - ujson=4.2.0
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - unixodbc=2.3.9
  - uriparser=0.9.3
  - urllib3=1.26.8
  - utf8proc=2.6.1
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.35.1
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=3.0.2
  - xlrd=2.0.1
  - xlsxwriter=3.0.2
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - coloredlogs==15.0.1
    - country-converter==0.7.4
    - humanfriendly==10.0
    - nptyping==1.4.4
    - numpyencoder==0.3.0
    - typish==1.9.3
