name: ario3
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2021.11=py38_0
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_1
  - anaconda-client=1.9.0=py38h06a4308_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=2.2.0=py38h06a4308_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - arrow=0.13.1=py38_0
  - arrow-cpp=4.0.1=py38hced866c_3
  - asn1crypto=1.4.0=py_0
  - astroid=2.6.6=py38h06a4308_0
  - astropy=5.0=py38h09021b7_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.3.5=py38h7f8727e_0
  - bkcharts=0.2=py38_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h8c45485_0
  - bokeh=2.4.2=py38h06a4308_0
  - boost-cpp=1.73.0=h27cfd23_11
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.15.0=py38hd667e15_1
  - cfitsio=3.470=hf0d0db6_6
  - chardet=4.0.0=py38h06a4308_1003
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.11.0=py38h06a4308_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - conda-token=0.3.0=pyhd3eb1b0_0
  - contextlib2=0.6.0.post1=pyhd3eb1b0_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - curl=7.71.1=h8f29fe8_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.25=py38hdbfa776_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - daal4py=2021.4.0=py38h78b71dc_0
  - dal=2021.4.0=h06a4308_729
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2021.10.0=py38h06a4308_0
  - docutils=0.18.1=py38h06a4308_2
  - double-conversion=3.1.5=he6710b0_1
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - expat=2.4.1=h2531618_2
  - fastcache=1.1.0=py38h7b6447c_0
  - filelock=3.4.2=pyhd3eb1b0_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2022.1.0=pyhd3eb1b0_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=21.8.0=py38h7f8727e_1
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - glob2=0.7=pyhd3eb1b0_0
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h2531618_2
  - gmpy2=2.0.8=py38hd5f6e3b_3
  - graphite2=1.3.14=h23475e2_0
  - greenlet=1.1.1=py38h295c915_0
  - grpc-cpp=1.26.0=hf8bcb03_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=py38h7918eee_0
  - harfbuzz=2.8.1=h6f93f22_0
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imagecodecs=2021.8.26=py38h4cda21f_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py38h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - inflection=0.5.1=py38h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.29.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py38h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38h06a4308_0
  - jupyter_server=1.4.1=py38h06a4308_0
  - jupyterlab=3.2.1=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.2=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - keyring=23.4.0=py38h06a4308_0
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.19.1=h3535a68_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.4.2=h62408e4_0
  - libboost=1.73.0=h3ff78a5_11
  - libcurl=7.71.1=h303737a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - liblief=0.10.1=he6710b0_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h3826bc1_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libthrift=0.13.0=hfb8234f_6
  - libtiff=4.2.0=h85742a9_0
  - libtool=2.4.6=h7b6447c_1005
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libxslt=1.1.34=hc22bd24_0
  - libzopfli=1.0.3=he6710b0_0
  - llvmlite=0.34.0=py38h269e1b5_4
  - locket=0.2.1=py38h06a4308_1
  - lxml=4.6.3=py38h9120a33_0
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.5.0=py38h06a4308_0
  - matplotlib-base=3.5.0=py38h3ed280b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.2.1=py38h06a4308_0
  - msgpack-python=1.0.2=py38hff7bd54_1
  - multipledispatch=0.6.0=py38_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py38h06a4308_1
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.3.0=py38h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - nltk=3.6.5=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.6=py38h06a4308_0
  - numba=0.51.2=py38h0573a6f_1
  - numexpr=2.8.1=py38h6abb31d_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - numpydoc=1.2=pyhd3eb1b0_0
  - odfpy=1.4.1=py_0
  - olefile=0.46=pyhd3eb1b0_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1m=h7f8727e_0
  - orc=1.6.7=h973521d_2
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py38h8c16a72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.45.3=hd140c19_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - patchelf=0.13=h295c915_0
  - path=16.2.0=pyhd3eb1b0_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathlib2=2.3.6=py38h06a4308_2
  - pathspec=0.7.0=py_0
  - patsy=0.5.2=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py38h5aabda8_0
  - pip=20.2.4=py38_0
  - pixman=0.40.0=h7f8727e_1
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - pluggy=1.0.0=py38h06a4308_0
  - ply=3.11=py38_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - progressbar2=3.37.1=py38h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.8.0=py38h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py38h403a769_0
  - pyarrow=4.0.1=py38he0739d4_3
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycurl=7.44.0=py38h8f2d780_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py38h27cfd23_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pylint=2.9.6=py38h06a4308_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pymrio=0.4.6=pyhd8ed1ab_0
  - pyodbc=4.0.32=py38h295c915_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytables=3.6.1=py38h9fd0a39_0
  - pytest=6.2.5=py38h06a4308_2
  - pytest-runner=5.3.1=pyhd3eb1b0_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-utils=2.5.6=py38h06a4308_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py38h7f8727e_1
  - pyzmq=22.3.0=py38h295c915_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - re2=2020.11.01=h2531618_1
  - readline=8.0=h7b6447c_0
  - regex=2021.11.2=py38h7f8727e_0
  - requests=2.27.1=pyhd3eb1b0_0
  - ripgrep=12.1.1=0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py38h06a4308_1
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - scikit-image=0.18.3=py38h51133e4_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - scikit-learn-intelex=2021.4.0=py38h06a4308_0
  - scipy=1.7.3=py38hc147768_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - secretstorage=3.3.1=py38h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=50.3.0=py38hb0f4dca_1
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=he6710b0_0
  - sniffio=1.2.0=py38h06a4308_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=3.5.3=pyhd3eb1b0_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=5.1.5=py38h06a4308_1
  - spyder-kernels=2.1.3=py38h06a4308_0
  - sqlalchemy=1.4.27=py38h7f8727e_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.13.0=py38h7f8727e_0
  - sympy=1.9=py38h06a4308_0
  - tbb=2021.5.0=hd09550d_0
  - tbb4py=2021.5.0=py38hd09550d_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.9.4=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py38h7f8727e_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ujson=4.2.0=py38h295c915_0
  - unicodecsv=0.14.1=py38_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.9=h7b6447c_0
  - uriparser=0.9.3=he6710b0_1
  - urllib3=1.26.8=pyhd3eb1b0_0
  - utf8proc=2.6.1=h27cfd23_0
  - watchdog=2.1.6=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.35.1=py_0
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - wurlitzer=3.0.2=py38h06a4308_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.2=pyhd3eb1b0_0
  - xlwt=1.3.0=py38_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.4.0=py38h7f8727e_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - coloredlogs==15.0.1
    - country-converter==0.7.4
    - humanfriendly==10.0
    - nptyping==1.4.4
    - numpyencoder==0.3.0
    - typish==1.9.3
